### ISSUE TITLE
Add opportunity set image size via format field

### ISSUE THREAD

**Issue by MrFranke** [m3-moretv/smogger#6]
For `image` string format add syntax options for size.
Example
```yaml
image:
  type: string
  format: image[200x300]
```
that spec return link to image with 200 height and 300 width
